// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using CatalogService.Data;

#nullable disable

namespace CatalogService.Data.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CatalogService.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("de305d54-75b4-431b-adb2-eb6b9e546013"),
                            Name = "Пицца",
                            RestaurantId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6")
                        },
                        new
                        {
                            Id = new Guid("f2a3b4c5-d6e7-4890-a1b2-c3d4e5f6a7b8"),
                            Name = "Напитки",
                            RestaurantId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6")
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            Name = "Суши",
                            RestaurantId = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e")
                        },
                        new
                        {
                            Id = new Guid("22222222-3333-4444-5555-666666666666"),
                            Name = "Роллы",
                            RestaurantId = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e")
                        },
                        new
                        {
                            Id = new Guid("33333333-4444-5555-6666-777777777777"),
                            Name = "Стейки",
                            RestaurantId = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a")
                        },
                        new
                        {
                            Id = new Guid("44444444-5555-6666-7777-888888888888"),
                            Name = "Гриль",
                            RestaurantId = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a")
                        });
                });

            modelBuilder.Entity("CatalogService.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            CategoryId = new Guid("de305d54-75b4-431b-adb2-eb6b9e546013"),
                            Description = "Томаты, моцарелла, базилик",
                            IsAvailable = true,
                            Name = "Маргарита",
                            Price = 450m,
                            RestaurantId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6")
                        },
                        new
                        {
                            Id = new Guid("88e0b674-135d-495c-9c0e-4366667520e1"),
                            CategoryId = new Guid("de305d54-75b4-431b-adb2-eb6b9e546013"),
                            Description = "Острые колбаски, много сыра",
                            IsAvailable = true,
                            Name = "Пепперони",
                            Price = 550m,
                            RestaurantId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6")
                        },
                        new
                        {
                            Id = new Guid("55d28b93-135d-495c-9c0e-111122223333"),
                            CategoryId = new Guid("f2a3b4c5-d6e7-4890-a1b2-c3d4e5f6a7b8"),
                            Description = "0.5л в бутылке",
                            IsAvailable = true,
                            Name = "Кока-кола",
                            Price = 120m,
                            RestaurantId = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6")
                        },
                        new
                        {
                            Id = new Guid("7a56976a-5494-4360-9149-14a004b0451e"),
                            CategoryId = new Guid("11111111-2222-3333-4444-555555555555"),
                            Description = "Лосось, сливочный сыр, огурец",
                            IsAvailable = true,
                            Name = "Филадельфия",
                            Price = 480m,
                            RestaurantId = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e")
                        },
                        new
                        {
                            Id = new Guid("33334444-5555-6666-7777-888899990000"),
                            CategoryId = new Guid("22222222-3333-4444-5555-666666666666"),
                            Description = "Угорь, авокадо, соус унаги",
                            IsAvailable = true,
                            Name = "Канада Ролл",
                            Price = 620m,
                            RestaurantId = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e")
                        },
                        new
                        {
                            Id = new Guid("d111d222-d333-d444-d555-d666d777d888"),
                            CategoryId = new Guid("33333333-4444-5555-6666-777777777777"),
                            Description = "Мраморная говядина (прожарка Medium)",
                            IsAvailable = true,
                            Name = "Стейк Рибай",
                            Price = 1450m,
                            RestaurantId = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a")
                        },
                        new
                        {
                            Id = new Guid("e111e222-e333-e444-e555-e666e777e888"),
                            CategoryId = new Guid("44444444-5555-6666-7777-888888888888"),
                            Description = "Баклажан, перец, кабачок",
                            IsAvailable = true,
                            Name = "Овощи Гриль",
                            Price = 320m,
                            RestaurantId = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a")
                        });
                });

            modelBuilder.Entity("CatalogService.Entities.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7a8b-9c0d-e1f2a3b4c5d6"),
                            Address = "ул. Ленина, 10",
                            IsActive = true,
                            Name = "Папа Пицца"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-8b9c-0d1e-2f3a4b5c6d7e"),
                            Address = "пр. Мира, 25",
                            IsActive = true,
                            Name = "Токио Хаус"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a7-b8c9-0d1e-2f3a-4b5c6d7e8f9a"),
                            Address = "ул. Кузнечная, 12",
                            IsActive = true,
                            Name = "Мясной Цех"
                        });
                });

            modelBuilder.Entity("CatalogService.Entities.Category", b =>
                {
                    b.HasOne("CatalogService.Entities.Restaurant", "Restaurant")
                        .WithMany("Categories")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("CatalogService.Entities.Product", b =>
                {
                    b.HasOne("CatalogService.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CatalogService.Entities.Restaurant", "Restaurant")
                        .WithMany("Products")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("CatalogService.Entities.Restaurant", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
